### ISSUE TITLE
Login to Windows Server w/ Kerberos doesn´t work

### ISSUE THREAD

**Issue by svenschumacher** [rundeck-plugins/rundeck-winrm-plugin#44]
I´ve setted up rundeck with winrm-plugin. 

**Settings for the project/etc/resources.xml:**

`<node name="hostname" connectionType="WINRM_NATIVE" node-executor="overthere-winrm" winrm-password-option="winrmPassword" winrm-protocol="http" winrm-auth-type="kerberos"  username="username@DOMAIN.TLD" winrmPassword="password" description="Rundeck server node Windows" tags="" hostname="hostname:Port" osArch="x86_64" osFamily="windows" osName="Microsoft Windows Server 2008 R2 Standard" osVersion="Microsoft Windows Server 2008 R2 Standard" />`

**In /etc/rundeck/profile**
-Djava.security.krb5.realm=domain.tld -Djava.security.krb5.kdc=domaincontroller.domain.tld

**Windows Server settings:**
```
winrm/config/service
...
AllowUnencrypted = true
...
Auth
    Basic = true
    Kerberos = true
...
DefaultPorts:
    HTTP = 5985
    HTTPS = 5986
AllowRemoteAccess = true
...
```

If i try to run the job, the following Error appears:
`Execution failed: 72207: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [_domain_: ConfigurationFailure: Password was not set]}, Node failures: {_domain_=[ConfigurationFailure: Password was not set]}, flow control: Continue, status: failed]`

**Comment by gschueler** [comment]
try changing `winrm-password-option="winrmPassword"` to `winrm-password-option="option.winrmPassword"`

**Comment by svenschumacher** [comment]
It didn´t help.

```
07:26:02			[overthere-winrm:host] Password was not set
07:26:02			Failed: ConfigurationFailure: Password was not set
```

**Comment by gschueler** [comment]
what is your job definition?

**Comment by svenschumacher** [comment]
Exported as yaml:

```
- description: ''
  executionEnabled: true
  id: 5974465d-abbb-4501-bc42-cf555b7d8126
  loglevel: DEBUG
  name: Test
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      threadcount: 1
    filter: srvansttest1
  nodesSelectedByDefault: true
  options:
  - name: Password
    secure: true
    value: PASSWORD
  scheduleEnabled: true
  sequence:
    commands:
    - exec: write-host test
    keepgoing: false
    strategy: step-first
  uuid: 5974465d-abbb-4501-bc42-cf555b7d8126
```
